"""Compatibility shim for OSMnx helper functions."""

from . import (
    _add_edge_grades_manual,
    _add_elevations_from_open_elevation,
    _add_elevations_from_raster_manual,
    _find_nearest_edge_numpy,
    _find_nearest_node_numpy,
    add_edge_bearings,
    add_edge_grades,
    add_edge_lengths,
    add_edge_speeds,
    add_edge_travel_times,
    add_node_elevations_google,
    add_node_elevations_raster,
    calculate_shortest_path,
    estimate_network_area,
    find_nearest_edge,
    find_nearest_node,
    get_basic_stats,
    get_bearing_distribution,
    get_edge_info,
    get_elevation_stats,
    get_grade_stats,
    get_graph_extent,
    get_node_coordinates,
    get_osmnx,
    is_graph_projected,
    load_graph_graphml,
    project_graph,
    save_graph_graphml,
)

__all__ = [
    "get_osmnx",
    "project_graph",
    "is_graph_projected",
    "add_edge_lengths",
    "add_edge_bearings",
    "add_edge_speeds",
    "add_edge_travel_times",
    "add_edge_grades",
    "_add_edge_grades_manual",
    "get_basic_stats",
    "get_bearing_distribution",
    "get_elevation_stats",
    "get_grade_stats",
    "find_nearest_node",
    "_find_nearest_node_numpy",
    "find_nearest_edge",
    "_find_nearest_edge_numpy",
    "get_node_coordinates",
    "get_edge_info",
    "calculate_shortest_path",
    "add_node_elevations_raster",
    "_add_elevations_from_raster_manual",
    "add_node_elevations_google",
    "_add_elevations_from_open_elevation",
    "save_graph_graphml",
    "load_graph_graphml",
    "get_graph_extent",
    "estimate_network_area",
]

